export interface ComponentTypes {
  codigo: string,
  unidades: string,
  valorPor100g: string,
  colherSopaCheia45g: string,
  copoAmericanoDuplo200ml: string,
  copoAmericanoPequeno130ml: string,
  pedacoUnidadeFatia: string,
  pratoFundo450g: string,
  pratoRaso350g: string,
}

export interface CardInfosType {
  cardName: 'acidosGraxosPoliinsaturados' | 'acidosGraxosMonoinsaturados' | 'acidosGraxosSaturados' | 'acucarDeAdicao' | 'alcool' | 'calcios' | 'carboidratoDisponivel' | 'carboidratoTotal' | 'cinzas' | 'cobre' | 'colesterol' | 'energiaKcal' | 'energiaKJs' | 'equivalenteDeFolato' | 'ferro' | 'fibraAlimentar' | 'fosforo' | 'lipidios' | 'magnesio' | 'manganes' | 'niacina' | 'potassio' | 'proteina' | 'riboflavina' | 'salDeAdicao' | 'selenio' | 'sodio' | 'tiamina' |  'umidade' | 'vitaminaARAE' | 'vitaminaARE' | 'vitaminaB12' | 'vitaminaB6' | 'vitaminaC' | 'vitaminaD' | 'vitaminaE' | 'zinco',
  infos: ComponentTypes
}

export interface CardFoodType {
  codigo: string,
  nome: string,
  nomeCientifico: string,
  grupo: string,
  marca: string,
}

export interface FoodWithComponentTypes {
  codigo: string,
  nome: string,
  nomeCientifico: string,
  grupo: string,
  marca: string
  acidosGraxosPoliinsaturados: ComponentTypes[],
  acidosGraxosMonoinsaturados: ComponentTypes[],
  acidosGraxosSaturados: ComponentTypes[],
  acidosGraxosTrans: ComponentTypes[],
  acucarDeAdicao: ComponentTypes[],
  alcool: ComponentTypes[],
  calcios: ComponentTypes[],
  carboidratoDisponivel: ComponentTypes[],
  carboidratoTotal: ComponentTypes[],
  cinzas: ComponentTypes[],
  cobre: ComponentTypes[],
  colesterol: ComponentTypes[],
  energiaKcal: ComponentTypes[],
  energiaKJs: ComponentTypes[],
  equivalenteDeFolato: ComponentTypes[],
  ferro: ComponentTypes[],
  fibraAlimentar: ComponentTypes[],
  fosforo: ComponentTypes[],
  lipidios: ComponentTypes[],
  magnesio: ComponentTypes[],
  manganes: ComponentTypes[],
  niacina: ComponentTypes[],
  potassio: ComponentTypes[],
  proteina: ComponentTypes[],
  riboflavina: ComponentTypes[],
  salDeAdicao: ComponentTypes[],
  selenio: ComponentTypes[],
  sodio: ComponentTypes[],
  tiamina: ComponentTypes[],
  umidade: ComponentTypes[],
  vitaminaARAE: ComponentTypes[],
  vitaminaARE: ComponentTypes[],
  vitaminaB12: ComponentTypes[],
  vitaminaB6: ComponentTypes[],
  vitaminaC: ComponentTypes[],
  vitaminaD: ComponentTypes[],
  vitaminaE: ComponentTypes[],
  zinco: ComponentTypes[],
}